### ISSUE TITLE
SubversionException: 160043 - Expected FS format between '1' and '7'; found format '8'

### ISSUE THREAD

**Issue by ogermann** [cmanley/viewvc-docker#2]
When we try to connect to our subversion repository we see the following python stacktrace:
```
An Exception Has Occurred
Python Traceback
Traceback (most recent call last):
  File "/usr/lib/viewvc/lib/viewvc.py", line 4855, in main
    request.run_viewvc()
  File "/usr/lib/viewvc/lib/viewvc.py", line 276, in run_viewvc
    self.repos.open()
  File "/usr/lib/viewvc/lib/vclib/svn/svn_repos.py", line 387, in open
    self.repos = repos.svn_repos_open(self.rootpath)
  File "/usr/lib/python2.7/dist-packages/libsvn/repos.py", line 261, in svn_repos_open
    return _repos.svn_repos_open(*args)
SubversionException: 160043 - Expected FS format between '1' and '7'; found format '8'
```
"Old" libsvn version?

**Comment by cmanley** [comment]
Perhaps it's an old libsvn version or a bug in viewvc. If it's the latter then it's probably better to create a new issue in the viewvc project along with the file system type you mounted. 
You can search for the error message and find other projects with similar error messages dating from 2012 even.
